services:
  client-app:
    image: surpentsphere/client-app
    build:
      context: .
      dockerfile: app/client-app/Dockerfile
    ports:
      - "3000:80"
    restart: always

  admin-app:
    image: surpentsphere/admin-app
    build:
      context: .
      dockerfile: app/admin-app/Dockerfile
    ports:
      - "3001:80"
    restart: always

  postservice.Api:
    image: postservice.Api
    build:
      context: .
      dockerfile: server/services/aspnet-services/PostService/PostService.Api/Dockerfile
